---
# tasks file for kubernetes_master

- name: Install required packages
  ansible.builtin.apt:
    name:
      - curl
      - gnupg2
      - software-properties-common
      - apt-transport-https
      - ca-certificates
    state: present
    update_cache: yes
  become: true

- name: Install Containerd
  ansible.builtin.apt:
    name: containerd
    state: present
  become: true

- name: Remove Keyrings Directory (if it exists)
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: absent
  become: true

- name: Remove Existing Kubernetes APT source file (if it exists)
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/pkgs_k8s_io_core_stable_v1_30_deb.list
    state: absent
  become: true

- name: Disable swap
  ansible.builtin.command: swapoff -a
  become: true

- name: Ensure swap is disabled on boot
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: '^/swap.img'
    line: '#/swap.img none swap sw 0 0'
  become: true

- name: Add kernel modules for Containerd
  ansible.builtin.copy:
    dest: /etc/modules-load.d/containerd.conf
    content: |
      overlay
      br_netfilter
  become: true

- name: Load kernel modules
  ansible.builtin.shell: modprobe overlay && modprobe br_netfilter
  become: true

- name: Add sysctl params for Kubernetes
  ansible.builtin.copy:
    dest: /etc/sysctl.d/kubernetes.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
  become: true

- name: Apply sysctl params
  ansible.builtin.command: sysctl --system
  become: true

- name: Generate containerd default config
  ansible.builtin.command: containerd config default > /opt/containerd/config.toml
  become: true

- name: Set SystemdCgroup to true in containerd config
  ansible.builtin.replace:
    path: /opt/containerd/config.toml
    regexp: 'SystemdCgroup = false'
    replace: 'SystemdCgroup = true'
  become: true

- name: Reload systemd and restart containerd
  ansible.builtin.systemd:
    daemon_reload: yes
    name: containerd
    state: restarted
  become: true

- name: Allow necessary Kubernetes ports through UFW
  ansible.builtin.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items:
    - 22
    - 6443
    - 2379:2380
    - 8080
    - 10250
    - 10251
    - 10252
    - 10255
    - 5473
    - 179
  become: true

- name: Enable and reload UFW
  ansible.builtin.ufw:
    state: enabled
  become: true

- name: Reload UFW
  ansible.builtin.command: ufw reload
  become: true

- name: Prepare keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: true

- name: Add Kubernetes apt-key
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
    mode: '0644'
    force: true
  become: true

- name: Add Kubernetes APT repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /"
    state: present
    filename: "kubernetes"
  become: true

- name: Update apt
  ansible.builtin.apt:
    update_cache: yes
  become: true

- name: Install Kubernetes components
  ansible.builtin.apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
  become: true

- name: Hold Kubernetes packages
  ansible.builtin.command: apt-mark hold kubelet kubeadm kubectl
  become: true

- name: Add cgroup driver config to kubelet
  ansible.builtin.copy:
    dest: /etc/default/kubelet
    content: 'KUBELET_EXTRA_ARGS="--cgroup-driver=cgroupfs"'
  become: true

- name: Reload systemd and restart kubelet
  ansible.builtin.systemd:
    daemon_reload: yes
    name: kubelet
    state: restarted
  become: true

- name: Set Kubernetes profile environment
  ansible.builtin.copy:
    dest: /etc/profile.d/kubernetes.sh
    content: |
      export KUBECONFIG=/etc/kubernetes/admin.conf
      export ANSIBLE_USER="manager"
  become: true

- name: Add fail-swap-on=false to kubelet config
  ansible.builtin.lineinfile:
    path: /usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf
    insertafter: '^\[Service\]'
    line: 'Environment="KUBELET_EXTRA_ARGS=--fail-swap-on=false"'
  become: true

- name: Reload systemd and restart kubelet again
  ansible.builtin.systemd:
    daemon_reload: yes
    name: kubelet
    state: restarted
  become: true

- name: Initialize Kubernetes control plane (no kube-proxy)
  ansible.builtin.command: kubeadm init --pod-network-cidr=10.0.0.0/16 --skip-phases=addon/kube-proxy
  register: kubeadm_init_output
  become: true
  changed_when: false

- name: Set permissions on admin.conf
  ansible.builtin.file:
    path: /etc/kubernetes/admin.conf
    mode: '0755'
    state: file
  become: true

- name: Generate the join command
  ansible.builtin.command: kubeadm token create --print-join-command
  register: join_command
  become: true

- name: Save join command to file
  ansible.builtin.copy:
    content: "{{ join_command.stdout }}"
    dest: /tmp/join-command
  become: true

- name: Print join command
  ansible.builtin.debug:
    msg: "Join command: {{ join_command.stdout }}"
