version: "3.9"
services:
  nexus2:
    image: sonatype/nexus3
    ports:
    - "8081:8081"
    - "8082:8082"
    networks:
      - app2
    volumes:
      - nexus-data:/nexus-data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  jenkins1:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    user: root
    volumes:
      - jenkins_data:/var/jenkins_home
    networks:
      - app2
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager


  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf.d/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./cert/cert.pem:/etc/nginx/conf.d/cert/cert.pem
      - ./cert/cert.key.pem:/etc/nginx/conf.d/cert/cert.key.pem
      - ./nexus_crt/nexus.pem:/etc/nginx/conf.d/cert/nexus.pem
      - ./nexus_crt/nexus-key.pem:/etc/nginx/conf.d/cert/nexus-key.pem
      - ./cert/test.pem:/etc/nginx/conf.d/cert/test.pem
      - ./cert/test-key.pem:/etc/nginx/conf.d/cert/test-key.pem
    restart: on-failure
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager          



networks:
  app2:
volumes:
  jenkins_data:
  nexus-data:
