apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqldata
  namespace: exam
spec:
  capacity:
    storage: 2Gi
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/docker/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbclaim
  namespace: exam
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi
