    - name: Install MySQL and Python connector
      apt:
        name: "{{ item }}"
        update_cache: yes
        cache_valid_time: 3600
        state: present
      with_items:
        - python3-mysqldb
        - mysql-server
      become: true

    - name: Ensure MySQL is started and enabled
      service:
        name: mysql
        state: started
        enabled: true
      become: true


    - name: Update MySQL root password
      mysql_user:
        name: root
        host: "{{ item }}"
        password: "{{ mysql_root_password }}"
        login_user: root
        login_password: "{{ mysql_root_password }}"
        check_implicit_admin: yes
        priv: "*.*:ALL,GRANT"
      with_items:
        - localhost
      become: true

    - name: add sample data
      mysql_db: 
        name: web_app
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"
     

    - name: add sample data to database
      copy:
        src: dump.sql
        dest: /tmp/dump.sql
    
    - name: insert sample data
      mysql_db:
        name: testdb
        state: import
        target: /tmp/dump.sql
        login_user: root
        login_password: "{{ mysql_root_password }}"
              
